export default {
  esm: 'rollup',
  cjs: 'rollup',
  autoprefixer: {
    remove: false,
    grid: true,
  },
  cssModules: { generateScopedName: '[name]__[local]--[hash:base64:8]' },
  extractCSS: true,
  extraExternals: [
    'antd',
    'lodash',
    'qs',
    'axios',
    'react',
    'react-dom',
    'react-router-dom',
    'history',
    'mobx',
    'mobx-react',
    'mobx-react-lite',
    'moment',
    'react-dnd',
    'react-dnd-html5-backend',
  ],
};
